language: ruby
rvm:
  - 2.3.1
services:
  - postgresql
before_script:
  - cp config/database.yml.example config/database.yml
  - psql -c 'create database test;' -U postgres
  - bundle exec rake db:setup RAILS_ENV=test
script: bundle exec rspec